version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    depends_on:
      - redis

  celery:
    build: .
    container_name: fastapi-celery
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
